title: William B. Salazar's Site
theme: minima
markdown: kramdown
description: Cool Github website

sass:
  style: compressed

# Add this to use your stylesheet:
include:
  - assets/css/style.scss

header_pages:
  - index.md
  - about.md
  - projects.md
  
